import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Placeholder project covers are SVGs generated by this project itself
    // (not user-uploaded), so it's safe to allow SVG optimization here.
    dangerouslyAllowSVG: true,
    contentDispositionType: "inline",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
